image: debian:stable

pages:
  script:
  - apt-get update
  - apt-get -y install darkslide make
  - make
  - cp -a presentation.html custom.css images public/
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - main
